package com.doodle.enums;

public enum MessageType {
    JOIN_ROOM, JOINED_ROOM,
    USER_INFOS, CHAT_BOX,
    CHOOSE_WORD_ROOM, CHOOSE_WORD_USER,
    CHOSEN_WORD,
    GUESS_WORD_ROOM, GUESS_WORD_USER,
    GUESSED_WORD,
    GUESSING_COMPLETED,
    ROUND_COMPLETED,
    GAME_COMPLETED,
    BOARD,
    TIME_UPDATE,
    HINT,
    WAITING
}
